### ISSUE TITLE
Stylelint version issue

### ISSUE THREAD

**Issue by patric-eberle** [billybonks/broccoli-stylelint#35]
We're using a configuration which is meant for Stylelint >= 8.0.0. Unfortunately this is not working in combination with ember-cli-stylelint, since broccoli-stylelint installs Stylelint < 8.0.0. Can you deploy a new release, which uses the new Stylelint?

**Comment by nathancharles** [comment]
I'm also seeing when the stylelint version in the NPM module is different from the git repo. When I install I get version 0.12.0, but the stylelint dependency is "stylelint": "~7.9.0"

**Comment by billybonks** [comment]
This has been resolved, sorry about the delay, there was a bug in stylelint, which I have temporarily fixed here. please use v1

**Comment by rwwagner90** [comment]
This is still an issue because the version is set wrong https://github.com/billybonks/broccoli-stylelint/blob/master/package.json#L44

**Comment by billybonks** [comment]
@rwwagner90 all good here now right?

**Comment by rwwagner90** [comment]
@billybonks not sure. I think I still get the issues, but haven't looked into which repos I get it in or why.

**Comment by rwwagner90** [comment]
I'm still seeing this:
```
warning " > stylelint-config-ship-shape@0.4.0" has unmet peer dependency "stylelint@^8.0.0".
warning "stylelint-config-ship-shape > stylelint-config-standard@17.0.0" has unmet peer dependency "stylelint@^8.0.0".
warning "stylelint-config-ship-shape > stylelint-scss@2.2.0" has unmet peer dependency "stylelint@^8.0.0".
warning "stylelint-config-ship-shape > stylelint-config-standard > stylelint-config-recommended@1.0.0" has unmet peer dependency "stylelint@^8.0.0".
```

**Comment by billybonks** [comment]
let me try this add on :)

**Comment by billybonks** [comment]
https://github.com/shipshapecode/ember-shepherd/pull/198

marking this as resolved, found the root cause of the above errors.

**Comment by billybonks** [comment]
okay i did deeper investigation. it seems that in yarn if you specify a peerDependency it requires the parent to specify that it depends on that dependency. 

if you use npm post v5.x if a sibling dependency of the one that specififed the peerDependency includes the target dependency as a dependency it will not warn you

talking to the folks at yarn about this. https://github.com/yarnpkg/yarn/issues/5514

if you want to fix it in the mean make sure the parent package includes the dependency specified in the child packages peerDependency.

**Comment by rwwagner90** [comment]
Nice find! Thanks, I will try that.
